
/* Georgian College
// Assignment 1 | COMP1073 Client-Side JavaScript
24F Client-Side JavaScript - 200
Student: Geraldo Beiro
Student ID: 200587023
*/


/* Variables
-------------------------------------------------- */
// Create a new speechSynthesis object
var synth = window.speechSynthesis;
// Learn more about SpeechSynthesis.speak() at https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/speak
var textToSpeak = '';
var sentenceParts = ["","","","",""]; // this array will store the random words


// ok, now I will create all the 5 arrays with the nouns, adjectives and so on..
const arrayOne = [
	"The turkey", "mom", "Dad", "The dog", "my teacher", "The elephant", "The cat"
];
const arrayTwo = [
	"sat on", "ate", "danced with", "saw", "doesn't like", "kissed"
];

const arrayThree = [
	"a funny", "a scary", "a goofy", "a slimy", "a barking", "a fat"
];
const arrayFour = [
	"goat", "monkey", "fish", "cow", "frog", "bug", "worm"
];
const arrayFive = [
	"on the moon", "on the chair", "in my spaghetti", "in my soup", "on the grass", "in my shoes"
];

/* Functions
-----------------------------------------------------*/
// now I will create the randomized functions for the buttons (pick a word from each array)
function getTheRandomWord(array){
	return array[Math.floor(Math.random()*array.length)];
}

// Function to update the displayed sentence
function updateSentenceDisplay() {
	textToSpeak = sentenceParts.join(' '); // Join the sentence parts together
	document.getElementById('sentenceDisplay').innerText = textToSpeak; // Display the sentence on the webpage
}

//to generate the whole sentence, I am creating these functions to pick the random words generated by the getTheRandomWord function
function pickFirstWord(){
	/*I am reassigning the value of textToSpeech*/
	const selectedWord = getTheRandomWord(arrayOne)
	sentenceParts[0] = selectedWord; 
	updateSentenceDisplay(); // Update the display with the current sentence
	speakNow(selectedWord); // this part will speak the current random word selected
}

function pickSecondWord(){
	/*I am reassigning the value of textToSpeech*/
	const selectedWord = getTheRandomWord(arrayTwo)
	sentenceParts[1] = selectedWord; 
	updateSentenceDisplay(); // Update the display with the current sentence
	speakNow(selectedWord); // this part will speak the current random word selected
}
function pickThirdWord(){
	/*I am reassigning the value of textToSpeech*/
	const selectedWord = getTheRandomWord(arrayThree)
	sentenceParts[2] = selectedWord; 
	updateSentenceDisplay(); // Update the display with the current sentence
	speakNow(selectedWord); // this part will speak the current random word selected
}
function pickFourthWord(){
	/*I am reassigning the value of textToSpeech*/
	const selectedWord = getTheRandomWord(arrayFour)
	sentenceParts[3] = selectedWord; 
	updateSentenceDisplay(); // Update the display with the current sentence
	speakNow(selectedWord); // this part will speak the current random word selected
}
function pickFifthWord(){
	/*I am reassigning the value of textToSpeech*/
	const selectedWord = getTheRandomWord(arrayFive)
	sentenceParts[4] = selectedWord; 
	updateSentenceDisplay(); // Update the display with the current sentence
	speakNow(selectedWord); // this part will speak the current random word selected
}

//-------------------------------------------------- */
function speakNow(string) {
	// Create a new speech object, attaching the string of text to speak
	var utterThis = new SpeechSynthesisUtterance(string);
	// Actually speak the text
	synth.speak(utterThis);
}

/* Event Listeners
-------------------------------------------------- */
// Onclick handler for the button that speaks the text contained in the above var textToSpeak
speakButton.onclick = function() {
	speakNow(textToSpeak);
}
